language: node_js
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn run test:ci
after_success:
- mv coverage/lcov-report build || true
branches:
  except:
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
env:
