language: node_js
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn install
script:
- yarn run test:ci
after_success:
- mv coverage/lcov-report build || true
branches:
  except:
  - gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
notifications:
  email: false
env:
  global:
    secure: cHTUwdNL5SitB13cdVnpoFuJj33df6Eo0PaPcbhYUSUfztEwPCC6hE64Q2ApnWF2qUI+HpTPirX6CBU2fjau6eOyr+N3L7gsq1yZn3vM3ZPZFUafc4iQQ5ZBoCCMdenGDz31aFmvqjtngZUyeCV33R2Gk1crLhrZFaUepiU+Kzb51d0+oDNBMw01Fxe5EuEo+Hj91EQX6ehIbCSVyes0XngMMPdJgqEfSjWzysZbp5ggylYQh1uhd+E26/NHd1iKk6FSyoLnUPbT4v+Pvkfy5Q2jnDmBCF3KTh/oDYZiwcvVjTD8igcnQLtPszXjm/B6whogQSE+Be1ZeBviYRoADWp0NC7mgJI2U3fTcDvEiSbTkAZuQn70ZMvzLiJhKY5ILKlQYfflXIElxCTy6krYYE/JAS+i2sja2+N6tgnIl30E/HvKmAlfkv4UUfob/+dMTIDFPiGgRwhYZB/tXfx27W+szCIynkPMYnoShfAtrs2kGeu7cLIkvHDDkrM5Eix1X5IZ3FTYe2IZaN9aT4oIVrYloVRKuuP4KpybxCsWYNwxcgTv8/56hvOqeewGJit5UizC/jb0azc1H0TFA6RcDUDC/pafJ24PaFb2Kfn7XlmBQSiKT3GgyJrfCs/AMqOSL4ORjBm2T3gW6BAFGZDMTvbNOjrSZ/KoNs4v6TdRQVg=
